config/routes.rb
Rse::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :confirmations , :only => [:show]

  

 
  match '/confirmation/:confirmation_token', :to => 'confirmations#show'

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/home',    :to => 'pages#home'

  root :to => 'pages#home'
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  
  
  has_secure_password
     
  attr_accessible :name, :password_digest,:password_confirmation,:password,
                  :confirmed_at,:confirmation_token,:confirmation_sent_at
  
  name_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name, 
    presence: true,
     uniqueness: {:case_sensitive => false}, 
     length: { :maximum => 30 }, 
     format: { :with => name_regex }
  
  validates :password,
    presence: true,
    length: { :within => 8..30 }


  before_save  :generate_token
  after_create :send_confirmation

  
  # Verifies whether a user is confirmed or not
  def confirmed?
    !!confirmed_at
  end   

  protected  
  def generate_token 
    begin
      token = SecureRandom.urlsafe_base64
    end while User.where(:confirmation_token => token).exists?

    self.confirmation_token = token
    self.confirmation_sent_at = Time.now.utc 
  end 

  protected
  def send_confirmation 
    UserMailer.confirmation_email(self).deliver
  end  

end

app/models/user_observer.rb
class UserObserver < ActiveRecord::Observer
  
  def before_create (user)  
    begin
      token = SecureRandom.urlsafe_base64
    end while user.where(:confirmation_token => token).exists?

    user.confirmation_token = token
    user.confirmation_sent_at = Time.now.utc 
  end 
  
  def after_create  (user)
    UserMailer.confirmation_email(@user).deliver
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery
  include SessionsHelper  

end

app/controllers/confirmations_controller.rb
class ConfirmationsController < ApplicationController

  # GET /confirmation?confirmation_token=abcdef
  def show
      
    @user = User.find_by_confirmation_token(params[:confirmation_token])   
    if @user.nil?
      redirect_to root_path, notice: "Are you registered? Check email and registration link"  
    else
      if @user.confirmed?
        redirect_to root_path, notice: "You are already confirmed! "  
      else
        @timestamp = Time.now.utc
        @user.update_column(:confirmed_at,@timestamp)
        @user.update_column(:updated_at, @timestamp)
        redirect_to signin_path   notice: "You are confirmed now, please sign in."          
      end
    end 
    
 end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home" 
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end

  def help
    @title = "Help"
  end
        
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
  end

  def create

    user = User.find_by_name(params[:session][:name])
    if user and user.authenticate(params[:session][:password])
    # If confirmed Sign the user in and redirect to the user's show page.    
      if user.confirmed?
        sign_in user      
        redirect_to user   
      else
        redirect_to root_path, notice: "Check you email and confirm account."       
      end       
    else
    # Create an error message and re-render the signin form.       
      flash.now[:error] = "Invalid email/password combination."  
      @title = "Sign in"
      render 'new'   

    end

  end

  def destroy
    sign_out
    redirect_to root_path, notice: "Logout"    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
 
#  def index
#    @users = User.all

#    respond_to do |format|
#       format.html # index.html.erb
#       format.json { render json: @users }
#     end
# end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
#     respond_to do |format|
#       format.html # show.html.erb
#       format.json { render json: @user }
#     end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @title = "Sign up"
    @user = User.new

 #   respond_to do |format|
 #     format.html # new.html.erb
 #     format.json { render json: @user }
 #   end
  end

  # GET /users/1/edit
#   def edit
#     @user = User.find(params[:id])
#   end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
        # user was successfully created
      if @user.save
#        sign_in @user
#        flash[:success] = "Welcome, #{@user.name} !"        
#        redirect_to @user
         flash[:success] = "Welcome, to #{@user.name} was send confirmation instructions !"           
         redirect_to root_path
      else
        @title = "Sign up"
        render 'new'
      end


#     respond_to do |format|
#       if @user.save
#        format.html { redirect_to @user, notice: 'User was successfully created.' }
 


#         format.json { render json: @user, status: :created, location: @user }
#       else
#         format.html { render action: "new" }
#         format.json { render json: @user.errors, status: :unprocessable_entity }
#       end
#     end
  end

  # PUT /users/1
  # PUT /users/1.json
#   def update
#     @user = User.find(params[:id])

#     respond_to do |format|
#       if @user.update_attributes(params[:user])
#         format.html { redirect_to @user, notice: 'User was successfully updated.' }
#        format.html { redirect_to users_url,
#            notice: "Пользователь #{@user.name} был успешно обновлен." }

#         format.json { head :no_content }
#       else
#         format.html { render action: "edit" }
#         format.json { render json: @user.errors, status: :unprocessable_entity }
#       end
#     end
#   end

  # DELETE /users/1
  # DELETE /users/1.json
#   def destroy
#     @user = User.find(params[:id])
#     @user.destroy

#     respond_to do |format|
#       format.html { redirect_to users_url }
#       format.json { head :no_content }
#     end
#   end
 end

app/helpers/application_helper.rb
module ApplicationHelper

  # Return a title on a per-page basis.
  def title
    base_title = "Project App"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
    


end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    session[:current_user_id] = user.id    
  end

  def current_user
    @current_user ||= session[:current_user_id] &&
      User.find_by_id(session[:current_user_id])
  end

  def signed_in?
    !current_user.nil?
  end  
  
  def sign_out
    @current_user = session[:current_user_id] = nil
  end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
  </head>
  <body>

	<%= link_to "Home", root_path %>
    <%= link_to "About", about_path %>
    <%= link_to "Contact", contact_path %>  
	<%= link_to "Help", help_path %>        
    
    <% if signed_in? %>
      <li><%= link_to "Profile", current_user %></li>
    <% end %>    

   <% if signed_in? %>
      <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
      <% else %>
      <li><%= link_to "Sign in", signin_path %></li>
    <% end %>    

    <%= debug(params) if Rails.env.development? %>

	<% flash.each do |key, value| %>
	  <div class="flash <%= key %>"><%= value %></div>
	<% end %>    
  
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
    <p>
      <a href="http://localhost:3000/">Project App</a>
      is a project to make a happy
      with <a href="http://rubyonrails.org/">Ruby on Rails</a>. 
    </p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
    <p>
      Contact about the Project app at the
      <a href="http://localhost:3000/feedback">feedback page</a>.
    </p>

app/views/pages/help.html.erb
<h1>Help</h1>
    <p>
    	Help page
    </p>

app/views/pages/home.html.erb
<h1>Project App</h1>
    <p>
      This is the home page for the
      <a href="http://localhost:3000/">Project</a>
      application.
    </p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

     <ul>
       <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
 <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>


<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= gravatar_image_tag @user.name %>
  <%= @user.name %>
</h1>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>